---
name: UNIVERSAL-isa
version: 0.06
author: ~
abstract: |-
  Attempt to recover from people calling UNIVERSAL::isa as a
  function
license: perl
requires:
  Scalar::Util: 0
  perl: 5.006
provides:
  UNIVERSAL::isa:
    file: lib/UNIVERSAL/isa.pm
    version: 0.06
generated_by: Module::Build version 0.2611
