---
name: UNIVERSAL-isa
version: 1.00_00
author:
  - 'Autrijus Tang <autrijus@autrijus.org>'
  - 'chromatic <chromatic@wgz.org>'
  - 'Yuval Kogman <nothingmuch@woobling.org>'
abstract: |-
  Attempt to recover from people calling UNIVERSAL::isa as a
  function
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Scalar::Util: 0
  perl: 5.006
provides:
  UNIVERSAL::isa:
    file: lib/UNIVERSAL/isa.pm
    version: 1.00_00
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
